আসসালামু আলাইকুম। 
আমি আপনাদের সাথে একটি html Starter pack শেয়ার করলাম। ফাইল টা খুব সুন্দরভাবে সাজিয়েছি। এই ফাইলে একটা সাইট বানাতে যেই, যেই প্লাগিন লাগে এবং মুটামুটি যতগুলি components লাগে। তার সব কিছুই দেয়া আছে এবং একটা Animated Responsive Sticky Menu, Search Bar আর সাথে Scroll Up ডিজাইন করা আছে। বলে রাখা ভালো, আমি এটাতে Bootstrap এর সব Components দেয়নি। শুধু Bootstrap এর bootstrap.grid.css এর ফাইলটা এড করেছি।bootstrap.grid.css ফাইলটাতে Responsive, Flex, Grid, Margin, Madding, Display ইত্যাদির কোড গুলি দেয়া আছে।(এই ফাইলের ভিতরে ঢুকে css গুলা একটু দেখলে, আপনার সব ক্লিয়ার হয়ে যাবে)। bootstrap এর সব কিছু ব্যবহার না করার কারণ হলো। একটা সাইট করতে গিয়ে bootstrap এর সবকিছু দরকার পরে না। অনেক কোড অযথা পরে থাকে। অযথা কোডে ওয়েবসাইট অনেক ভারী হয়ে যায়। এতে করে আমার আপনার কোনো সমস্যা নাই। কিন্তু সাইটের লোডিং স্পীড অনেক বেড়ে যাবে। একটা সাইট ফাস্ট লোড হওয়া অনেক গুরুত্বপূর্ণ বিষয়। ফাস্ট লোডের জন্যই এই starter pack টা বানানো। ইনশাআল্লাহ আাশা করি আপনাদের অনেক ভালো লাগবে।
👉 আমার এই Starter Pack এ default.css ফাইলে কিছু কমন css Style করা আছে। যেইগুলা সবসময় ব্যবহার হয়। যেমনঃ- box-shadow, margin, float, padding, text alignment, border-radius, typography, selection, transition,
img responsive, tranaform X-Y center, transform-X center, transform-Y center, 
👉 HTML Starterp Pack --------------
Download link -----
https://github.com/saruarhosenn/html-starter-pack
Visit link -----
https://saruarhosenn.github.io/html-starter-pack/
👉 তাছাড়া একটা ওয়েবসাইটে আরও কিছু Components লাগে। যেমনঃ- Tab, Popup Modal, Accordion, Custom select option, Custom check box, Radio button ইত্যাদি। এই প্রত্যেকটারও ডিজাইন করা আছে। নিচে Download & Visit link দিলাম। Download করে নিয়েন।
1) Tab ----------
Download link -----
https://github.com/saruarhosenn/animated-tab-with-js
Visit link ----- https://saruarhosenn.github.io/animated-tab-with-js/
2) Popup Modal ----------
Download link -----
https://github.com/saruarhosenn/Popup-Modal
Visit link ----- https://saruarhosenn.github.io/Popup-Modal/
3) Custom Select Option ----------
Download link -----
https://github.com/saruarhosenn/custom-select-option
Visit link ----- https://saruarhosenn.github.io/custom-select-option/
4) Redio Button ----------
Download link -----
https://github.com/saruarhosenn/Input-Radio--button
Visit link ----- https://saruarhosenn.github.io/Input-Radio--button/
4) Custom Check box ----------
Download link -----
https://github.com/saruarhosenn/check-box
Visit link ----- https://saruarhosenn.github.io/check-box/
5) Accordion ----------
Download link -----
https://github.com/saruarhosenn/Accordion-css-js
Visit link ----- https://saruarhosenn.github.io/Accordion-css-js/
আরও ২টা Animation Puls Button
1) Animation Puls Button ----------
Download link  -----
https://github.com/saruarhosenn/Animation-Puls-Btn
Visit link ----- https://saruarhosenn.github.io/Animation-Puls-Btn/
2) Animation Puls Button
Download link -----
https://github.com/saruarhosenn/Animation_video_btn
Visit link ----- https://saruarhosenn.github.io/Animation_video_btn/
👉 ফাইলের কোনো কোড অথবা ডিজাইন যদি বুজতে অসুবিধা হয়। তাহলে আমাকে সরাসরি ইনবক্সে নক দিবেন। ইনশাআল্লাহ সুন্দর করে বুজিয়ে দিব। প্রয়োজনে লাইভে এসে বুজাব।
